version: '3.9'

services:
  
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD", "psqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 10s
      retries: 3
        
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db
  
volumes:
  pgdata: {}
